#!usr/bin/env bash

fibonacci(){
    acumulado=$1
    acumulador=$2
    termoAtual=$3
    termoF=$4
    
    while [[ $termoAtual -lt $termoF ]]; do
        echo "$acumulado"
            acumulador2=$((acumulado+acumulador))
            acumulado=$acumulador
            termoAtual=$((termoAtual+1))
            fibonacci $acumulado $acumulador2 $termoAtual $termoF
    done
}

fibonacci 0 1 1 10
